yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
# handler403csrf = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include("about.urls", namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
LEN_TEXT = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:LEN_TEXT]

    class Meta():
        ordering = ['-pub_date']
        default_related_name = 'posts'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django.forms import ModelForm

from posts.models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        labels = {'group': 'Группа', 'text': 'Текст поста'}
        help_texts = {'group': 'Выберите группу',
                      'text': 'Введите текст поста'}
        fields = ('group', 'text', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from .paginators import get_paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.views.decorators.cache import cache_page


@cache_page(20)
def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = get_paginator(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group')
    page_obj = get_paginator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group')
    page_obj = get_paginator(posts, request)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        pk=post_id
    )
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form, })
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect("posts:profile", post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)

    context = {
        'form': form,
        'post_id': post_id,
        'post': post,
        'is_edit': True,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-body">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}
              </div>
              {% if is_edit %}
              {% if request.user == post.author %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{% url 'posts:post_edit' post_id %}">
                {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста<span class="required text-danger" >*</span>
                    </label>
                    {{ form.text }}
                    <span class="helptext text-muted">Текст нового поста</span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">Group</label>
                    {{ form.group }}
                    <span class="helptext text-muted">
                      Группа, к которой будет относиться пост
                    </span>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %} 
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
              </form>
              {% endif %}
              {% else %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form 
              method="post"
              enctype="multipart/form-data"
              action="{% url 'posts:post_create' %}">
              {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Текст поста<span class="required text-danger" >*</span>
                  </label>
                  {{ form.text }}
                  <span class="helptext text-muted">Текст нового поста</span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_group">Group</label>
                  {{ form.group }}
                  <span class="helptext text-muted">
                    Группа, к которой будет относиться пост
                  </span>
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_image">
                    Картинка                      
                  </label>
                  <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    Добавить
                  </button>
                </div>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} 
  Записи сообщества {{ group.title }} 
{% endblock title %} 
{% block content %}
<div class="container py-5">
<h1>Записи сообщества: {{ group.title }}</h1>
<p>
  {{ group.description }}
</p>
    {% for post in page_obj %} 
    <article>
      {% include 'includes/posts_card.html' %}
        <a href="{% url 'posts:post_detail' post.pk %}">
          подробная информация 
        </a>
    </article>
        {% if post.group %}       
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
{% endfor %}
{% include 'includes/paginator.html' %}
  </div>  
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% block title %} 
  Последние обновления на сайте 
{% endblock title %} 
{% block content %}
{% load cache %}  
<div class="container py-5">      
  <h1>Последние обновления на сайте</h1> 
  <article> 
  {% cache 20 index_page with page_obj %}
  {% for post in page_obj %} 
    {% include 'includes/posts_card.html' %}
    <a href="{% url 'posts:post_detail' post.pk %}">
          подробная информация 
    </a>
  </article>
  <article>  
  {% if post.group %} 
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
  {% endif %} 
  </article> 
  {% if not forloop.last %} 
    <hr> 
  {% endif %} 
  {% endfor %}
   {% endcache %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
<div class="container col-lg-9 col-sm-12">
  <div class="row">
    <aside class="col-12 col-md-4">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <b>Дата публикации:</b><br> {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            <b>Группа:</b>
            <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          <b>Автор:</b>
          <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
        </li>
        <li class="list-group-item">
          <b>Всего постов автора:</b> {{  post.author.posts.count }}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-8">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if post.author == user %}
      <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
      {% endif %}
    </article>
  </div>
  {% load user_filters %}
  {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
  {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %} 
{% block title %} 
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %} 
  <div class="container py-5">        
    <h1>Все посты пользователя: {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>   
    {% for post in page_obj %} 
    <article>
      {% include 'includes/posts_card.html' %}
        <a href="{% url 'posts:post_detail' post.pk %}">
          подробная информация 
        </a>
    </article>
        {% if post.group %}       
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        {% endif %}
    {% if not forloop.last %}
    <hr>
    {% endif %}
{% endfor %}
{% include 'includes/paginator.html' %} 
  </div> 
{% endblock content %}